name: inside the free fitness movement
favicon: null
layout_spectrum: 0.57901
typography_spectrum: 0.72131
title: Inside The Free Fitness Movement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021011'
    - '#6f6857'
    - '#d2c0a9'
    - '#1268cd'
    - '#58a7ec'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
