name: bmandaric
favicon: null
layout_spectrum: 0.10867
typography_spectrum: 0.72131
title: Bojan Mandaric
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#000000'
    - '#e2bb48'
    - '#fb5a5c'
    - '#60823d'
  brandStrength: 1
  lightness: 0.8954365148674697
  saturation: 0
  rhythmicContrast: 0.9887177920900285
purpose: []
